"""
GitHub Pages Static Site Generator
=====================================
Generates a public HTML site from the reports/ folder.

Each race weekend gets its own page with:
  - Prediction vs actual result card (per stage)
  - Embedded prediction charts (PNG)

The index page lists all races with links to the latest prediction stage.

Usage:
    python scripts/generate_github_pages.py

Output: docs/index.html + docs/races/{race_slug}_{year}/index.html
Deployed automatically via GitHub Actions → GitHub Pages.
"""

from __future__ import annotations

import csv
import sys
import shutil
from datetime import datetime, timezone
from pathlib import Path

# Allow importing f1_pipeline from project root
sys.path.insert(0, str(Path(__file__).parent.parent))

REPORTS_DIR = Path("reports")
DOCS_DIR = Path("docs")
RACES_DIR = DOCS_DIR / "races"

# Stage display labels (most-recent-first priority order)
STAGE_PRIORITY = [
    "post_race", "qualifying", "sprint", "sprint_qualifying",
    "fp3", "fp2", "fp1", "pre_weekend",
]
STAGE_LABELS = {
    "pre_weekend": "Pre-Weekend",
    "fp1": "After FP1",
    "fp2": "After FP2",
    "fp3": "After FP3",
    "sprint_qualifying": "After Sprint Qualifying",
    "sprint": "After Sprint",
    "qualifying": "After Qualifying",
    "post_race": "Post-Race",
}

CSS = """
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       background: #0f0f1a; color: #e0e0e0; margin: 0; padding: 0; }
header { background: #1a1a2e; border-bottom: 2px solid #e10600; padding: 16px 32px;
         display: flex; align-items: center; gap: 16px;
         position: sticky; top: 0; z-index: 100; }
header h1 { margin: 0; font-size: 1.4rem; color: #fff; }
header .subtitle { color: #aaa; font-size: 0.85rem; }
main { max-width: 1100px; margin: 32px auto; padding: 0 24px; }
h2 { color: #e10600; font-size: 1.1rem; margin-top: 2em; border-bottom: 1px solid #333; padding-bottom: 6px; }
h3 { color: #fff; }
.race-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 16px; margin: 24px 0; }
.race-card { background: #1a1a2e; border: 1px solid #2a2a4e; border-radius: 8px; padding: 16px;
             text-decoration: none; color: #e0e0e0; transition: border-color 0.2s; }
.race-card:hover { border-color: #e10600; }
.race-card .round { font-size: 0.75rem; color: #888; margin-bottom: 4px; }
.race-card .name { font-size: 1rem; font-weight: 600; color: #fff; }
.race-card .date { font-size: 0.8rem; color: #aaa; margin-top: 4px; }
.race-card .stage-badge { display: inline-block; margin-top: 8px; background: #e10600; color: #fff;
                           font-size: 0.7rem; padding: 2px 8px; border-radius: 12px; }
.race-card .sprint-badge { display: inline-block; margin-top: 4px; background: #ff8c00; color: #fff;
                            font-size: 0.7rem; padding: 2px 8px; border-radius: 12px; margin-left: 4px; }
.stage-tabs { display: flex; gap: 8px; flex-wrap: wrap; margin: 16px 0; }
.stage-tab { padding: 6px 14px; border-radius: 20px; font-size: 0.8rem; text-decoration: none;
             background: #2a2a4e; color: #aaa; border: 1px solid #3a3a6e; }
.stage-tab.active { background: #e10600; color: #fff; border-color: #e10600; }
.chart-row { display: flex; gap: 16px; flex-wrap: wrap; margin: 16px 0; }
.chart-row img { max-width: 100%; border-radius: 8px; border: 1px solid #2a2a4e; }
footer { text-align: center; padding: 32px; color: #555; font-size: 0.8rem; border-top: 1px solid #1a1a2e; margin-top: 40px; }
a { color: #4a9eff; }
"""


def _page_html(title: str, body: str, show_home: bool = False) -> str:
    home_link = ' · <a href="/timecopilot-f1-2026-forecast/" style="color:#aaa">← Home</a>' if show_home else ""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>{CSS}</style>
</head>
<body>
<header>
  <div>
    <h1>🏎️ F1 TimeCopilot Predictions</h1>
    <div class="subtitle">AI-powered Formula 1 forecasting · Powered by
      <a href="https://timecopilot.dev/" style="color:#e10600">TimeCopilot</a>
    </div>
  </div>
  <div style="margin-left:auto; font-size:0.8rem; color:#888;">
    <a href="https://github.com/sebhgtz/timecopilot-f1-2026-forecast" style="color:#aaa">GitHub ↗</a>{home_link}
  </div>
</header>
<main>
{body}
</main>
<footer>
  Generated by <a href="https://timecopilot.dev/">TimeCopilot</a> ·
  Data sources: FastF1, OpenF1, Jolpica-F1 ·
  Updated {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}
</footer>
</body>
</html>
"""


def _load_accuracy_log() -> dict[tuple[str, int], dict]:
    """Load accuracy_log.csv keyed by (slug, year). Returns best (latest) row per race."""
    log_path = REPORTS_DIR / "accuracy_log.csv"
    results: dict[tuple[str, int], dict] = {}
    if not log_path.exists():
        return results
    with open(log_path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            key = (row["race_slug"], int(row["year"]))
            results[key] = row  # later rows overwrite earlier ones (most recent stage wins)
    return results


def _load_actual_podium(race_dir: Path) -> list[dict]:
    """Load actual P1/P2/P3 from race_results_post_race.json if available."""
    import json
    path = race_dir / "race_results_post_race.json"
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        classified = [r for r in data.get("results", []) if r.get("position") is not None]
        classified.sort(key=lambda r: r["position"])
        return classified[:3]
    except Exception:
        return []


def _build_result_card_html(race_dir: Path, stage: str, accuracy_entry: dict | None) -> str:
    """
    Two-column card: left = this stage's predicted podium (P1/P2/P3), right = actual podium.
    Right column uses race_results_post_race.json when available (shows P1/P2/P3 actual).
    Falls back to accuracy_log for P1 only if JSON not present.
    """
    import json

    # Left column: read podium from race_forecast_{stage}.json
    pred_driver = None
    podium_entries = []
    fc_path = race_dir / f"race_forecast_{stage}.json"
    if fc_path.exists():
        try:
            fc = json.loads(fc_path.read_text(encoding="utf-8"))
            podium_entries = fc.get("podium", [])
            if not podium_entries:
                pw = fc.get("predicted_winner", {})
                if pw.get("driver_code"):
                    podium_entries = [{"position": 1, "driver_code": pw["driver_code"],
                                       "probability": pw.get("win_probability", 0)}]
            if podium_entries:
                pred_driver = podium_entries[0].get("driver_code")
        except Exception:
            pass

    if pred_driver is None:
        return ""

    stage_label = STAGE_LABELS.get(stage, stage.upper())
    podium_lines = ""
    for entry in podium_entries[:3]:
        code = entry.get("driver_code", "?")
        prob = (entry.get("probability") or 0) * 100
        pos = entry.get("position", "?")
        podium_lines += (
            f'<span style="display:block; margin-bottom:3px;">'
            f'P{pos}: <strong>{code}</strong>'
            f'<span style="color:#888; font-size:0.78rem;"> ({prob:.0f}%)</span>'
            f'</span>'
        )

    left_html = f"""
    <div>
      <div style="color:#888; font-size:0.72rem; text-transform:uppercase; letter-spacing:0.05em; margin-bottom:6px;">
        🔮 Predicted ({stage_label})
      </div>
      {podium_lines}
    </div>"""

    # Right column: actual podium from race_results_post_race.json (preferred)
    actual_podium = _load_actual_podium(race_dir)
    if actual_podium:
        actual_p1 = actual_podium[0]["driver_code"]
        stage_correct = (pred_driver == actual_p1)
        icon = "✅" if stage_correct else "❌"
        verdict = "Correct!" if stage_correct else f"Wrong ({actual_p1} won)"
        bg = "#1a3a1a" if stage_correct else "#3a1a1a"
        pred_codes = {e.get("driver_code"): e.get("position") for e in podium_entries[:3]}
        podium_rows = ""
        for ap in actual_podium:
            p = ap["position"]
            code = ap["driver_code"]
            pred_pos = pred_codes.get(code)
            match = " ✓" if pred_pos == p else ""
            podium_rows += (
                f'<span style="display:block; margin-bottom:3px;">'
                f'P{p}: <strong>{code}</strong>'
                f'<span style="color:#5a5; font-size:0.78rem;">{match}</span>'
                f'</span>'
            )
        right_html = f"""
    <div>
      <div style="color:#888; font-size:0.72rem; text-transform:uppercase; letter-spacing:0.05em; margin-bottom:6px;">
        🏁 Actual Podium
      </div>
      {podium_rows}
      <span style="color:#aaa; font-size:0.78rem; margin-top:4px; display:block;">{icon} {verdict}</span>
    </div>"""
    elif accuracy_entry and accuracy_entry.get("actual_winner") not in (None, "", "?"):
        # Fallback: only P1 from accuracy_log (old races without race_results_post_race.json)
        actual = accuracy_entry["actual_winner"]
        stage_correct = (pred_driver == actual)
        icon = "✅" if stage_correct else "❌"
        verdict = "Correct!" if stage_correct else f"Wrong ({actual} won)"
        bg = "#1a3a1a" if stage_correct else "#3a1a1a"
        right_html = f"""
    <div>
      <div style="color:#888; font-size:0.72rem; text-transform:uppercase; letter-spacing:0.05em; margin-bottom:6px;">
        🏁 Actual Result
      </div>
      <span style="display:block; margin-bottom:3px;">P1: <strong>{actual}</strong></span>
      <span style="color:#aaa; font-size:0.78rem; margin-top:4px; display:block;">{icon} {verdict}</span>
    </div>"""
    else:
        bg = "#1a1a2e"
        right_html = """
    <div>
      <div style="color:#888; font-size:0.72rem; text-transform:uppercase; letter-spacing:0.05em; margin-bottom:6px;">
        🏁 Actual Podium
      </div>
      <em style="color:#555;">Race not yet run</em>
    </div>"""

    return f"""<div style="display:grid; grid-template-columns:1fr 1fr; gap:12px;
  background:{bg}; border:1px solid #2a2a4e; border-radius:8px;
  padding:14px 18px; margin:0 0 16px; font-size:0.9rem;">
  {left_html}
  {right_html}
</div>"""


def _build_race_comparison_html(race_dir: Path) -> str:
    """
    Side-by-side predicted vs actual finishing order for the post-race tab.
    Left: predicted top 10 from top10_qualifying.csv (or best available stage).
    Right: actual classified + DNF + DNS from race_results_post_race.json.
    """
    import json as _json
    import csv as _csv

    # Load predicted top 10 from best available stage CSV
    predicted_rows = []
    best_stage_label = "Qualifying"
    for stage_name, label in (("qualifying", "After Qualifying"), ("sprint", "After Sprint"),
                               ("fp3", "After FP3"), ("fp2", "After FP2"),
                               ("fp1", "After FP1"), ("pre_weekend", "Pre-Weekend")):
        top10_path = race_dir / f"top10_{stage_name}.csv"
        if top10_path.exists():
            try:
                with top10_path.open(encoding="utf-8") as f:
                    for row in _csv.DictReader(f):
                        predicted_rows.append({
                            "rank": int(float(row.get("predicted_rank", 99))),
                            "driver_code": row.get("driver_code", "?"),
                            "constructor": row.get("constructor", ""),
                            "prob": float(row.get("win_probability", 0)) * 100,
                        })
                predicted_rows.sort(key=lambda r: r["rank"])
                best_stage_label = label
            except Exception:
                pass
            if predicted_rows:
                break

    # Load actual results
    actual_classified, actual_dnf, actual_dns = [], [], []
    actual_results_path = race_dir / "race_results_post_race.json"
    if actual_results_path.exists():
        try:
            data = _json.loads(actual_results_path.read_text(encoding="utf-8"))
            for r in data.get("results", []):
                if r.get("position") is not None:
                    actual_classified.append(r)
                elif r.get("status", "").lower() == "did not start":
                    actual_dns.append(r)
                else:
                    actual_dnf.append(r)
            actual_classified.sort(key=lambda r: r["position"])
        except Exception:
            pass

    if not predicted_rows and not actual_classified:
        return ""

    predicted_set = {r["driver_code"] for r in predicted_rows}
    actual_by_driver = {r["driver_code"]: r for r in actual_classified}
    dnf_drivers = {r["driver_code"] for r in actual_dnf}
    dns_drivers = {r["driver_code"] for r in actual_dns}

    td = "padding:4px 10px; vertical-align:middle;"
    td_border = td + " border-left:1px solid #2a2a4e;"
    td_center = td_border + " text-align:center; white-space:nowrap;"

    rows_html = ""

    # One row per predicted driver (sorted by predicted rank)
    for pred in predicted_rows:
        driver = pred["driver_code"]
        act = actual_by_driver.get(driver)

        pred_cell = (
            f'P{pred["rank"]}'
            f'<span style="color:#888; font-size:0.8rem;"> ({pred["prob"]:.0f}%)</span>'
        )

        if act:
            pts = int(act.get("points", 0))
            pts_str = f'<span style="color:#888; font-size:0.8rem;"> · {pts}pts</span>' if pts > 0 else ""
            act_cell = f'P{act["position"]}{pts_str}'
            delta = pred["rank"] - act["position"]
            if delta == 0:
                delta_cell = "✅"
            elif delta > 0:
                delta_cell = f'<span style="color:#4aff9a;">⬆️ {delta}</span>'
            else:
                delta_cell = f'<span style="color:#ff6b6b;">⬇️ {abs(delta)}</span>'
        elif driver in dns_drivers:
            act_cell = '<span style="color:#888;">DNS</span>'
            delta_cell = '<span style="color:#888;">❌</span>'
        elif driver in dnf_drivers:
            act_cell = '<span style="color:#888;">DNF</span>'
            delta_cell = '<span style="color:#888;">❌</span>'
        else:
            act_cell = '<span style="color:#555;">—</span>'
            delta_cell = ""

        rows_html += (
            f'<tr>'
            f'<td style="{td}">{pred_cell}</td>'
            f'<td style="{td}"><strong>{driver}</strong></td>'
            f'<td style="{td_border}">{act_cell}</td>'
            f'<td style="{td_center}">{delta_cell}</td>'
            f'</tr>\n'
        )

    # Unranked actual finishers (classified but not in prediction)
    unranked = [r for r in actual_classified if r["driver_code"] not in predicted_set]
    if unranked:
        rows_html += (
            f'<tr><td colspan="4" style="padding:6px 10px 2px; color:#555; '
            f'font-size:0.75rem; border-top:1px solid #1a1a3e;">'
            f'Not in forecast range:</td></tr>\n'
        )
        for r in sorted(unranked, key=lambda x: x["position"]):
            pts = int(r.get("points", 0))
            pts_str = f'<span style="color:#888; font-size:0.8rem;"> · {pts}pts</span>' if pts > 0 else ""
            rows_html += (
                f'<tr>'
                f'<td style="{td}; color:#555;">—</td>'
                f'<td style="{td}; color:#aaa;"><strong>{r["driver_code"]}</strong></td>'
                f'<td style="{td_border}; color:#aaa;">P{r["position"]}{pts_str}</td>'
                f'<td style="{td_center}"></td>'
                f'</tr>\n'
            )

    # DNF/DNS for drivers not already in predicted set
    for r in actual_dnf + actual_dns:
        if r["driver_code"] not in predicted_set:
            label = "DNS" if r["driver_code"] in dns_drivers else "DNF"
            rows_html += (
                f'<tr>'
                f'<td style="{td}; color:#555;">—</td>'
                f'<td style="{td}; color:#888;"><strong>{r["driver_code"]}</strong></td>'
                f'<td style="{td_border}; color:#888;">{label}</td>'
                f'<td style="{td_center}"></td>'
                f'</tr>\n'
            )

    th = "padding:5px 10px; text-align:left; color:#aaa; font-weight:500; border-bottom:1px solid #2a2a4e;"
    th_border = th + " border-left:1px solid #2a2a4e;"
    return f"""<div style="background:#1a1a2e; border:1px solid #2a2a4e; border-radius:8px; padding:16px 20px; margin:0 0 16px;">
  <div style="font-size:0.8rem; font-weight:600; color:#888; text-transform:uppercase; letter-spacing:0.05em; margin-bottom:10px;">
    📊 Race Prediction vs Result
  </div>
  <table style="width:100%; border-collapse:collapse; font-size:0.88rem;">
    <thead>
      <tr>
        <th style="{th}">🔮 {best_stage_label}</th>
        <th style="{th}">Driver</th>
        <th style="{th_border}">🏁 Actual</th>
        <th style="{th_border} text-align:center;">Δ</th>
      </tr>
    </thead>
    <tbody>{rows_html}</tbody>
  </table>
</div>"""


_DRIVER_CONSTRUCTOR_2026 = {
    "VER": "Red Bull Racing", "HAD": "Red Bull Racing",
    "HAM": "Ferrari",         "LEC": "Ferrari",
    "NOR": "McLaren",         "PIA": "McLaren",
    "RUS": "Mercedes",        "ANT": "Mercedes",
    "ALO": "Aston Martin",    "STR": "Aston Martin",
    "GAS": "Alpine",          "COL": "Alpine",
    "SAI": "Williams",        "ALB": "Williams",
    "BEA": "Haas",            "OCO": "Haas",
    "HUL": "Audi",            "BOR": "Audi",
    "LAW": "Racing Bulls",    "LIN": "Racing Bulls",
    "BOT": "Cadillac",        "PER": "Cadillac",
}

_CONSTRUCTOR_SLUG_DISPLAY = {
    "mercedes": "Mercedes",
    "red_bull_racing": "Red Bull Racing",
    "red_bull": "Red Bull Racing",
    "ferrari": "Ferrari",
    "mclaren": "McLaren",
    "aston_martin": "Aston Martin",
    "alpine": "Alpine",
    "williams": "Williams",
    "racing_bulls": "Racing Bulls",
    "rb": "Racing Bulls",
    "kick_sauber": "Audi",
    "sauber": "Audi",
    "audi": "Audi",
    "haas": "Haas",
    "haas_f1_team": "Haas",
    "cadillac": "Cadillac",
    "cadillac_f1": "Cadillac",
}


def _build_constructor_championship_html(race_dir: Path) -> str:
    """Constructor predicted vs current standings table for post-race tab."""
    path = race_dir / "constructor_championship_standings.csv"
    if not path.exists():
        return ""
    rows = []
    try:
        with path.open(encoding="utf-8") as f:
            for row in csv.DictReader(f):
                slug = row.get("unique_id", "").replace("constructor_", "")
                display = _CONSTRUCTOR_SLUG_DISPLAY.get(slug, slug.replace("_", " ").title())
                curr = float(row.get("current_points", 0))
                rows.append({
                    "name": display,
                    "current": curr,
                    "predicted": max(float(row.get("predicted_points", 0)), curr),
                    "pred_pos": int(float(row.get("predicted_position", 99))),
                })
        rows.sort(key=lambda r: r["pred_pos"])
    except Exception:
        return ""
    if not rows:
        return ""

    # If all predicted == current, the constructor forecast failed — derive from driver sums
    all_same = all(abs(r["predicted"] - r["current"]) < 0.1 for r in rows)
    if all_same:
        driver_path = race_dir / "championship_final_standings.csv"
        cons_totals: dict = {}
        try:
            with driver_path.open(encoding="utf-8") as f:
                for dr in csv.DictReader(f):
                    driver = dr.get("unique_id", "").replace("driver_", "")
                    constructor = _DRIVER_CONSTRUCTOR_2026.get(driver)
                    if not constructor:
                        continue
                    curr = float(dr.get("current_points", 0))
                    pred = max(float(dr.get("predicted_points", 0)), curr)
                    if constructor not in cons_totals:
                        cons_totals[constructor] = {"current": 0.0, "predicted": 0.0}
                    cons_totals[constructor]["current"] += curr
                    cons_totals[constructor]["predicted"] += pred
        except Exception:
            pass
        if cons_totals:
            rows = [
                {"name": k, "current": v["current"], "predicted": v["predicted"]}
                for k, v in cons_totals.items()
            ]
            rows.sort(key=lambda r: r["predicted"], reverse=True)
            for i, r in enumerate(rows):
                r["pred_pos"] = i + 1

    all_zero = all(r["current"] == 0 for r in rows)
    th = "padding:5px 10px; text-align:left; color:#aaa; font-weight:500; border-bottom:1px solid #2a2a4e;"
    th_num = th + " text-align:right;"
    if all_zero:
        header_html = (
            f'<th style="{th}">Pos</th>'
            f'<th style="{th}">Constructor</th>'
            f'<th style="{th_num}">Predicted Final</th>'
        )
    else:
        header_html = (
            f'<th style="{th}">Pos</th>'
            f'<th style="{th}">Constructor</th>'
            f'<th style="{th_num}">Current Pts</th>'
            f'<th style="{th_num}">Predicted Final</th>'
        )

    tbody = ""
    td = "padding:5px 10px; vertical-align:top;"
    td_num = td + " text-align:right;"
    for r in rows:
        curr_cell = f'<td style="{td_num}">{r["current"]:.0f}</td>' if not all_zero else ""
        tbody += (
            f'<tr>'
            f'<td style="{td}">{r["pred_pos"]}</td>'
            f'<td style="{td}"><strong>{r["name"]}</strong></td>'
            f'{curr_cell}'
            f'<td style="{td_num}">{r["predicted"]:.0f}</td>'
            f'</tr>\n'
        )

    return f"""<div style="background:#1a1a2e; border:1px solid #2a2a4e; border-radius:8px; padding:16px 20px; margin:0 0 16px;">
  <div style="font-size:0.8rem; font-weight:600; color:#888; text-transform:uppercase; letter-spacing:0.05em; margin-bottom:10px;">
    🏗️ Constructor Championship Prediction
  </div>
  <table style="width:100%; border-collapse:collapse; font-size:0.88rem;">
    <thead><tr>{header_html}</tr></thead>
    <tbody>{tbody}</tbody>
  </table>
</div>"""


def _result_banner_html(accuracy: dict) -> str:
    """Render a result banner from an accuracy_log row."""
    predicted = accuracy["predicted_winner"]
    actual = accuracy["actual_winner"]
    correct = accuracy["correct"].lower() == "true"
    stage = STAGE_LABELS.get(accuracy["session_stage"], accuracy["session_stage"].upper())
    icon = "✅" if correct else "❌"
    verdict = "Correct" if correct else "Wrong"
    color = "#1a3a1a" if correct else "#3a1a1a"
    border = "#2a6a2a" if correct else "#6a2a2a"
    pos = accuracy.get("actual_position_of_predicted", "")
    pos_note = f" (finished P{pos})" if pos and pos != "1" else ""
    return f"""<div style="background:{color}; border:1px solid {border}; border-radius:8px;
  padding:12px 18px; margin-bottom:16px; font-size:0.9rem;">
  {icon} <strong>Result ({stage}):</strong>
  Predicted <strong>{predicted}</strong> · Actual winner <strong>{actual}</strong>{pos_note} · {verdict}
</div>"""


def _get_round(slug: str, year: int) -> int:
    """Return the round number for a race slug+year using the F1 calendar."""
    try:
        from f1_pipeline.collectors.calendar_manager import F1Calendar
        cal = F1Calendar(year)
        for race in cal.races:
            if race.slug == slug:
                return race.round
    except Exception:
        pass
    # Fallback for known backtests
    return {
        ("abu_dhabi", 2025): 24,
        ("azerbaijan", 2025): 17,
        ("belgium", 2025): 13,
        ("monaco", 2025): 8,
        ("australia", 2026): 1,
    }.get((slug, year), 99)


def _discover_races() -> list[dict]:
    """
    Scan reports/ to find all race directories with their stages.
    Returns list of dicts (unsorted — build_index handles grouping/ordering).
    """
    races = []
    for race_dir in sorted(REPORTS_DIR.iterdir()):
        if not race_dir.is_dir():
            continue

        # Parse slug and year from dir name e.g. australia_2026
        parts = race_dir.name.rsplit("_", 1)
        if len(parts) != 2 or not parts[1].isdigit():
            continue

        slug = parts[0]
        year = int(parts[1])

        # Find available stages (prefer race_forecast_*.json, fall back to social_card_*.txt)
        stages_present = []
        for stage in STAGE_PRIORITY:
            if (race_dir / f"race_forecast_{stage}.json").exists() or \
               (race_dir / f"social_card_{stage}.txt").exists():
                stages_present.append(stage)

        if not stages_present:
            continue

        latest_stage = stages_present[0]  # highest priority = most recent

        races.append({
            "slug": slug,
            "year": year,
            "round": _get_round(slug, year),
            "dir": race_dir,
            "name": slug.replace("_", " ").title() + " Grand Prix",
            "stages": stages_present,
            "latest_stage": latest_stage,
        })

    return races


def build_race_page(race: dict, accuracy_log: dict) -> None:
    """Generate the race detail page."""
    out_dir = RACES_DIR / race["dir"].name
    out_dir.mkdir(parents=True, exist_ok=True)

    # Copy chart images
    charts_src = race["dir"] / "charts"
    charts_dst = out_dir / "charts"
    if charts_src.exists():
        if charts_dst.exists():
            shutil.rmtree(charts_dst)
        shutil.copytree(charts_src, charts_dst)

    # Accuracy log entry for this race (used by per-stage result card)
    result_key = (race["dir"].name.rsplit("_", 1)[0], race["year"])
    accuracy_entry = accuracy_log.get(result_key)

    latest_stage = race["latest_stage"]

    # Build stage tabs — onclick JS for show/hide
    tabs_html = '<div class="stage-tabs">'
    for stage in reversed(race["stages"]):  # chronological order in tabs
        label = STAGE_LABELS.get(stage, stage.upper())
        active = " active" if stage == latest_stage else ""
        tabs_html += (
            f'<a onclick="showTab(\'{stage}\', this)" class="stage-tab{active}" '
            f'style="cursor:pointer;">{label}</a>'
        )
    tabs_html += "</div>"

    # Build content for each stage; non-latest sections hidden by default
    content_html = ""
    for stage in race["stages"]:
        label = STAGE_LABELS.get(stage, stage.upper())
        display = "block" if stage == latest_stage else "none"

        # Charts for this stage
        chart_html = ""
        if charts_dst.exists():
            chart_files = sorted(charts_dst.glob(f"*_{stage}.png"))
            if chart_files:
                chart_html = '<div class="chart-row">'
                for cf in chart_files:
                    chart_html += f'<img src="charts/{cf.name}" alt="{cf.stem}" loading="lazy">'
                chart_html += "</div>"

        # Per-stage prediction vs actual result card
        result_card_html = _build_result_card_html(race["dir"], stage, accuracy_entry)

        # Post-race comparison table (predicted vs actual finishing order)
        comparison_html = ""
        constructor_html = ""
        if stage == "post_race":
            comparison_html = _build_race_comparison_html(race["dir"])
            constructor_html = _build_constructor_championship_html(race["dir"])

        content_html += f"""
<section id="{stage}" style="display:{display};">
  <h2>{label}</h2>
  {result_card_html}
  {comparison_html}
  {constructor_html}
  {chart_html}
</section>
"""

    result_html = _result_banner_html(accuracy_entry) if accuracy_entry else ""

    tab_js = """<script>
function showTab(id, el) {
  document.querySelectorAll('section[id]').forEach(function(s) { s.style.display = 'none'; });
  document.getElementById(id).style.display = 'block';
  document.querySelectorAll('.stage-tab').forEach(function(t) { t.classList.remove('active'); });
  el.classList.add('active');
}
</script>"""

    body = f"""
<h2 style="font-size:1.6rem; border:none; color:#fff;">
  🏁 {race['name']} <span style="color:#888;font-size:1rem;">{race['year']}</span>
</h2>
{result_html}{tabs_html}
{content_html}
{tab_js}
"""

    html = _page_html(f"{race['name']} {race['year']} — F1 TimeCopilot", body, show_home=True)
    (out_dir / "index.html").write_text(html, encoding="utf-8")
    print(f"  ✓ {race['dir'].name}/index.html")


def _race_cards_html(races: list[dict]) -> str:
    """Render a grid of race cards for a given list of races."""
    html = '<div class="race-grid">'
    for race in races:
        stage = race["latest_stage"]
        label = STAGE_LABELS.get(stage, stage.upper())
        href = f"races/{race['dir'].name}/"
        round_label = f"Rd {race['round']}" if race["round"] != 99 else str(race["year"])
        html += f"""
<a href="{href}" class="race-card">
  <div class="round">{round_label}</div>
  <div class="name">{race['name']}</div>
  <span class="stage-badge">{label}</span>
</a>"""
    html += "</div>"
    return html


def _accuracy_banner_html(accuracy_log: dict, year: int) -> str:
    """Render a per-year accuracy summary banner."""
    year_rows = {k: v for k, v in accuracy_log.items() if k[1] == year}
    # Only show races that have already happened (have an actual_winner)
    completed = {k: v for k, v in year_rows.items() if v.get("actual_winner")}
    if not completed:
        return '<p style="color:#666; font-size:0.85rem; margin:4px 0 12px;">No completed races yet.</p>'
    total = len(completed)
    correct = sum(1 for r in completed.values() if r["correct"].lower() == "true")
    pct = round(correct / total * 100)
    items = ""
    for row in sorted(completed.values(), key=lambda r: int(r["round"])):
        icon = "✅" if row["correct"].lower() == "true" else "❌"
        items += (
            f'<span style="margin-right:16px; white-space:nowrap;">'
            f'{icon} {row["race_name"].replace(" Grand Prix", " GP")}: '
            f'<strong>{row["predicted_winner"]}</strong>'
            f'</span>'
        )
    return f"""<div style="background:#1a1a2e; border:1px solid #2a2a4e; border-radius:8px;
  padding:14px 18px; margin:8px 0 16px;">
  <div style="font-size:0.95rem; font-weight:600; color:#fff; margin-bottom:6px;">
    🎯 {correct}/{total} race winners correctly predicted ({pct}%)
    <span style="font-size:0.75rem; color:#888; font-weight:400; margin-left:8px;">after qualifying</span>
  </div>
  <div style="font-size:0.85rem; color:#ccc; flex-wrap:wrap; display:flex;">
    {items}
  </div>
</div>"""


def build_index(races: list[dict], accuracy_log: dict) -> None:
    """Generate the home index page, grouped by year (newest first)."""
    n_races = len(races)
    n_reports = sum(len(r["stages"]) for r in races)

    # Group by year, each group sorted most recent round first
    years = sorted({r["year"] for r in races}, reverse=True)
    sections_html = ""
    for year in years:
        year_races = sorted(
            [r for r in races if r["year"] == year],
            key=lambda r: r["round"],
            reverse=True,
        )
        year_label = f"🏆 {year} Season"
        accuracy_html = _accuracy_banner_html(accuracy_log, year)
        sections_html += f"<h2>{year_label}</h2>\n{accuracy_html}{_race_cards_html(year_races)}\n"

    all_completed = {k: v for k, v in accuracy_log.items() if v.get("actual_winner")}
    all_total = len(all_completed)
    all_correct = sum(1 for r in all_completed.values() if r["correct"].lower() == "true")
    global_banner = (
        f'<p style="color:#aaa; font-size:0.9rem; margin:0 0 16px;">'
        f'🎯 <strong>{all_correct}/{all_total}</strong> race winners correctly predicted</p>'
    ) if all_total else ""

    body = f"""
<h2 style="font-size:1.5rem; border:none; color:#fff; margin-top:0;">
  F1 TimeCopilot Predictions
</h2>
{global_banner}<p style="color:#aaa;">
  AI-powered Formula 1 predictions for every race weekend.
  Updated after each session (FP1 → Sprint → Qualifying → Race).
  Forecasts generated by <a href="https://timecopilot.dev/">TimeCopilot</a>
  using historical FastF1 + OpenF1 data.
</p>
<p style="color:#666; font-size:0.85rem;">
  {n_races} race(s) · {n_reports} prediction update(s) · Last updated {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}
</p>
{sections_html}
<h2>About</h2>
<p>
  Predictions are generated using <a href="https://timecopilot.dev/">TimeCopilot</a>,
  the #1 ranked time series forecasting agent on the GIFT-Eval benchmark (NeurIPS 2025).
  Historical data covers 2015–2025 from FastF1 (lap times, session pace) and
  Jolpica-F1 (championship standings). Strategy data from OpenF1 API.
</p>
<p style="color:#888; font-size:0.85rem;">
  Source code: <a href="https://github.com/sebhgtz/timecopilot-f1-2026-forecast">GitHub</a>
</p>
"""

    html = _page_html("F1 2026 TimeCopilot Predictions", body)
    (DOCS_DIR / "index.html").write_text(html, encoding="utf-8")
    print(f"  ✓ docs/index.html ({n_races} races)")


def main() -> None:
    print("\n🌐 Generating GitHub Pages static site...")
    DOCS_DIR.mkdir(exist_ok=True)
    RACES_DIR.mkdir(exist_ok=True)

    # .nojekyll prevents GitHub Pages from ignoring underscored paths
    (DOCS_DIR / ".nojekyll").touch()

    races = _discover_races()
    if not races:
        print("  ⚠️  No reports found in reports/ — nothing to generate.")
        return

    accuracy_log = _load_accuracy_log()

    for race in races:
        build_race_page(race, accuracy_log)

    build_index(races, accuracy_log)
    print(f"\n✅ Site generated → {DOCS_DIR}/index.html ({len(races)} races)")
    print(f"   Deploy with: GitHub Pages → source: /docs")


if __name__ == "__main__":
    main()
